// Generated by CoffeeScript 1.6.2
(function() {
  var SelfText;

  SelfText = (function() {
    function SelfText() {
      var Exception;

      try {
        this.check_cmef();
      } catch (_error) {
        Exception = _error;
        this.fail();
      }
      this.validated();
    }

    SelfText.prototype.validated = function() {
      return $(".show-on-valid").show();
    };

    SelfText.prototype.fail = function() {
      return $(".show-on-failure").show();
    };

    SelfText.prototype.check_cmef = function() {
      if (!cmef.initialized) {
        throw new Exception('CMEF failed to initialized.');
      }
    };

    return SelfText;

  })();

  cmef.ready(function() {
    return window.selftest = new SelfText();
  });

}).call(this);
